image: gitpod/workspace-full

tasks:
  - name: Start proxy service
    before: docker run -d --name proxy -p 3128:3128 -p 4444:4444 -e TOR_INSTANCES=10 -e TOR_REBUILD_INTERVAL=1800 zhaowde/rotating-tor-http-proxy
    command: echo "Proxy service started"

  - name: Run scraper
    before: docker build -t scraper-app .
    init: docker create --name scraper -v "$(pwd)/data:/app/data" --env-file .env -e PROXY_URL=http://localhost:3128 scraper-app
    command: docker start -a scraper

ports:
  - port: 3128
    onOpen: ignore
  - port: 4444
    onOpen: ignore

vscode:
  extensions:
    - eamodio.gitlens
    - vscode-docker
