[package]
name = "advrider"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
indicatif = "0.17.8"
regex = "1.10.4"
reqwest = { version = "0.12.4", features = ["blocking", "json"] }
select = "0.6.0"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
tokio = { version = "1.37.0", features = ["full"] }
