FROM rustlang/rust:nightly-bookworm AS builder

ENV CARGO_TARGET_DIR=/cache \
    PATH=/root/.cargo/bin:$PATH \
    USER=root

WORKDIR /rust

RUN git clone https://github.com/trouchet/rust-hello.git .
COPY Cargo.* .
RUN cargo build && rm -rf /rust

WORKDIR /app
COPY . .
RUN cargo build

EXPOSE 3030
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
    CMD curl -f http://localhost:3030/health || exit 1

CMD ["cargo", "run", "--bin", "scraper"]
