services:
  proxy:
    platform: linux/amd64
    image: osminogin/tor-simple
    ports:
      - 0.0.0.0:9050:9050

  spider:
    depends_on:
      - proxy
    build:
      context: .
      dockerfile: Dockerfile.spider
    ports:
      - 0.0.0.0:3030:3030
      - 0.0.0.0:3031:3031
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    env_file: .env
    restart: on-failure

  scraper:
    platform: linux/arm64
    depends_on:
      - proxy
      - spider
      - redis
    build:
      context: .
      dockerfile: Dockerfile.scraper
    volumes:
      - ./data:/app/data
    env_file: .env
    environment:
      PROXY_URL: socks5://proxy:9050
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      SCCACHE_REDIS: redis://redis:6379
    restart: on-failure

  redis:
    image: redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./data/redis:/data
    ports:
      - 0.0.0.0:6379:6379
    restart: unless-stopped
