services:
  scraper:
    depends_on:
      - proxy
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    env_file: .env
    environment:
      PROXY_URL: socks5://rotatingproxy:9050
    restart: on-failure

  proxy:
    image: osminogin/tor-simple
    ports:
      - 0.0.0.0:9050:9050


