services:
  proxy:
    image: dockage/tor-privoxy:latest
    ports:
      - 0.0.0.0:9050:9050
      - 0.0.0.0:9051:9051
      - 0.0.0.0:8118:8118

  scraper:
    platform: linux/arm64
    depends_on:
      - proxy
    build:
      context: .
      dockerfile: Dockerfile.scraper
      args:
        PROXY_URL: socks5://127.0.0.1:9050
    volumes:
      - ./data:/app/data
      - ./cache:/cache
    env_file: .env
    restart: on-failure

