---

prompts:
  - |
    You are an AI assistant designed to extract information about useful gadgets and non-standard parts for the Husqvarna 701 Enduro motorcycle from posts on the ADVRider forum. Your task is to identify any parts or gadgets that the author mentions positively.

    ## INSTRUCTIONS:

    - Identify each item by its brand and provide a brief description of the part or accessory. Format each item as follows: "<BRAND>: <DESCRIPTION>".
    - Focus on non-standard parts and gadgets, such as rally towers. Exclude standard parts like wheels, which come pre-installed on the motorcycle.
    - Your goal is to extract parts and gadgets that could potentially enhance the performance or functionality of the motorcycle.
    - Present your output as a simple list, without any additional wording or context.
    - If no relevant parts or gadgets can be identified in the post, return the word "<NOPE>" and nothing else.
    - If you're unsure whether a part or gadget is relevant, it's better to err on the side of caution and exclude it from the list.

    ## EXAMPLES:

    Input:

    I'm resisting putting a Rekluse Clutch in the 701 as I'm trying to avoid tempting myself to do more technical stuff than 4wd roads. I have my 450 for that type of stuff and will probably add a Rekluse to that at some point. I had a Rekluse Auto Clutch in my old 400XC and it was great for that. I'm ready to spend what I need to make the 701 run like I want it too.

    Output:

    - Rekluse Auto Clutch: Automatic clutch for hard terrain

    ## INPUT: {{post}}


defaultTest:
  options:
    provider: openai:chat:gpt-3.5-turbo

providers:
  # Does not pass
  # - id: ollama:llama3:latest
  #   label: llama3-temp-0-1
  #   config:
  #     temperature: 0.1
  #     max_tokens: 4000

  # - id: openai:chat:gpt-3.5-turbo
  #   label: gpt-3-5-turbo-temp-0-7
  #   config:
  #     temperature: 0.7

  - id: openai:chat:gpt-3.5-turbo
    label: gpt-3-5-turbo-temp-0-1
    config:
      temperature: 0.1

  # - id: openai:chat:gpt-4-turbo
  #   label: gpt-4-turbo-temp-0-7
  #   config:
  #     temperature: 0.7

  # - id: openai:chat:gpt-4-turbo
  #   label: gpt-4-turbo-temp-0-1
  #   config:
  #     temperature: 0.1

  # - id: openai:chat:gpt-4
  #   label: gpt-4-temp-0-7
  #   config:
  #     temperature: 0.7

  # - id: openai:chat:gpt-4
  #   label: gpt-4-temp-0-1
  #   config:
  #     temperature: 0.01
scenarios:
  - config:
    - vars:
        post: "Okay. So the Renthall Fatbar RC fits with 2.5\" Risers. Wires are fine and the HDB guards line up well. Bar is still a little off I will probably have to reset my forks/triple clamp. Not enough to matter, but enough that I am annoyed. While I am at it, was gonna do a quick update of everything in case anyone has any questions: Renthall Fatbar RC Bar: We will see HDB Ultimate Guards with top clamp, 2.5\" riser and flip out mirrors: Guards and top clamp are great. Mirrors are mehhh. Husqvarna Aluminum Radiator Guard: Does it's job Fork bleeders: Do their job Trailjammer aluminum stator and clutch cover: install was easy, holding up great Fork Saver zip on fork socks: put them on every bike, love em Steg Pegz: Love em, keeps me standing longer. Steat Concept Seat: Must Have Wings Exhaust: No explanation needed Wings carbon exhaust cover: Could take it or leave it. Had a lot of loose straands that needed cut. Perun rear plate + extension: very secure, love the setup. Only complaint is the extension plate can't fit a rotopax mount, but the base plate can. Vanasche Motorsports Shortened Kickstand: A MUST HAVE Vanasche Motorsports Kickstand plate: Good for sand/loose dirt Vanasche Motorsports minimalist racks: holding up very well, protecting the body great as I have wrecked a few times with them. I fabricated a set of rotopax plates for them which I will upload later. Vanasche Motorsports enlarged brake pedal: works good Pivot Pegz: Some people hate em/some love em. Still getting use to them but so far great for standing. Still might have to go back to my larger pegz though and put the pivot pegz on the 1190. Rottweiler Intake: Works good. Leaves enough space that I can store spare set of tubes under the seat and I carry a pack of prefilters in the secret compartment on the left side. PCV: Not much to say. Combined with the intake and exhaust, def more power. SAS/Canister delete: Did on thew 1190, reduces garbage on the bike. Mosko Moto tool roll: It is pricey and bulky, but it's bombproof and had the organization I wanted. Mosko Moto 10L Drybag: Fits the tool roll, Slime air pump/patch kit, Thor Rain pack jacket, tow traps. Mosko Moto 40L Duffel: Fits all my camping gear for 3ish days or travel stuff for the wife and I if staying in a hotel. Rok straps: Always have a couple sets. Upcoming: Turn Signals Motoz Tractionator Desert H/T Shorty clutch/brake lever Larger shift lever Rear Disc Guard and ABS line protector"
        gadgets: |
          - Renthall Fatbar RC: Adjustable handlebar
          - HDB Ultimate Guards with top clamp, 2.5" riser and flip out mirrors
          - Husqvarna Aluminum Radiator Guard: Radiator protector
          - Fork bleeders: Fork pressure relief valves
          - Trailjammer aluminum stator and clutch cover: Protective covers for stator and clutch
          - Fork Saver zip on fork socks: Protective covers for forks
          - Steg Pegz: Foot pegs designed for standing
          - Seat Concept Seat: Comfortable motorcycle seat
          - Wings Exhaust: Performance exhaust system
          - Wings carbon exhaust cover: Carbon cover for exhaust system
          - Perun rear plate + extension: Secure rear plate with extension
          - Vanasche Motorsports Shortened Kickstand: Shortened kickstand for better balance
          - Vanasche Motorsports Kickstand plate: Plate for kickstand, useful in sand/loose dirt
          - Vanasche Motorsports minimalist racks: Durable racks for carrying gear
          - Vanasche Motorsports enlarged brake pedal: Enlarged brake pedal for better control
          - Pivot Pegz: Rotating foot pegs
          - Rottweiler Intake: Performance air intake system
          - PCV: Power Commander V for fuel management
          - SAS/Canister delete: Emission control delete kit
          - Mosko Moto tool roll: Durable tool roll for organization
          - Mosko Moto 10L Drybag: Waterproof bag for carrying tools and gear
          - Mosko Moto 40L Duffel: Large duffel bag for camping gear or travel items
          - Rok straps: Adjustable straps for securing gear.
    tests:
      - assert:
        - type: factuality
          value: "{{gadgets}}"
        - type: llm-rubric
          value: No wrapper text followed by :, like "<START>Output:", "<START>Commit message:" or "<START>##"
        - type: llm-rubric
          value: "Ensure output has a similar mening to {{gadgets}}"

tests:
  - vars:
      post: >-
        Just installed a Rade Garage tank on my 701 and it's a game changer for
        those long rides. The extra fuel capacity without compromising the
        bike's agility is amazing. Also installed a Baja Designs Squadron Pro
        LED light, which turns night into day. Thinking of adding a Lynx R
        Fairing next for some wind protection on those long stretches.
  - vars:
      post: >-
        I was hesitant at first, but after adding the Perun Moto luggage rack
        and a set of Mosko Moto Reckless 80 bags, my 701 Enduro feels ready for
        a multi-day adventure. The rack's design keeps the weight low and
        doesnt interfere with riding, even on technical trails. Also, the
        heat-resistant material on the Reckless 80 bags means I don’t have to
        worry about exhaust heat damaging my gear.
  - vars:
      post: >-
        After breaking my foot last season, I decided to invest in safety and
        comfort. Installed Pivot Pegz Mark 3, which offer wider and more stable
        footing. I've also upgraded to a Seat Concepts Comfort seat to help with
        those longer days in the saddle. Finally, for a bit of bling and
        functionality, I slapped on some Zeta aluminum handguards with
        integrated turn signals.
  - vars:
      post: >-
        Just finished installing the Nomad ADV rally tower on my 701. The build
        quality is top-notch, and the additional wind protection it provides has
        been a game changer on longer rides. I've also swapped out the stock
        seat for a Seat Concepts Comfort seat and threw on a set of Barkbusters
        to protect my hands on those bush trails. Can't forget the Garmin Zumo
        XT I mounted for navigation, a vast improvement over my old setup.
  - vars:
      post: >-
        Was skeptical at first, but after adding the Rottweiler Performance
        intake system, I'm impressed with the increase in horsepower. Also
        upgraded to a Wings exhaust, which not only reduced weight but sounds
        phenomenal. For navigation, I opted for the Rally Raid billet GPS mount,
        perfect for my Garmin. On a side note, installed a Scottoiler to keep
        the chain in optimal condition without constant manual maintenance.
  - vars:
      post: >-
        I've been reading about people installing Flexx Handlebars for better
        shock absorption on rough terrains. Still deciding on that. Meanwhile,
        I've added a high-clearance Lynx R fairing, which has drastically
        improved the bike's aerodynamics and protection against debris. For
        lighting, I upgraded to Baja Designs Squadron Pro LED lights, making
        night riding safer. Opted for a Giant Loop Coyote Saddlebag for luggage,
        perfect for those multi-day adventures.
  - vars:
      post: >-
        Just finished installing a Scotts Steering Stabilizer along with a
        ProTaper handlebar. The stabilizer makes a huge difference in handling,
        especially on rough terrain. Feels like a totally different bike now.
        Also, replaced the stock tires with a set of Dunlop D606s, and the
        improvement in traction is phenomenal. Can't recommend these changes
        enough for anyone looking to enhance their 701.
  - vars:
      post: >-
        Managed to get my hands on a Rally Raid tank kit for my 701 Enduro -
        adds an extra 10 liters of fuel capacity, which is fantastic for
        long-distance adventures. Also upgraded the exhaust to an Akrapovič, and
        the weight reduction plus the sound is just music to my ears. Lastly,
        I've fitted a Seat Concepts comfort seat, and the difference on longer
        rides is night and day. Highly recommended for anyone touring on their
        701.
  - vars:
      post: >-
        Spent the weekend tweaking the 701 for better off-road capability. A
        Rade Garage front fairing kit was the first addition, really changes the
        look and feel, plus offers great wind protection. Installed a Baja
        Designs Squadron Pro LED light for better night visibility — like
        turning night into day. Also added a set of Heidenau K60 tires for
        improved grip in variable conditions. The bike is almost unrecognizable
        now, and I'm extremely pleased with the performance enhancements.
  - vars:
      post: >-
        Just installed a Rottweiler Performance intake system on my 701 Enduro.
        The difference is night and day! Throttle response is much more
        immediate, and it feels like the bike breathes better overall. Next up,
        I'm considering a custom map to further tune the performance. Also,
        swapped out the stock mirrors for Doubletake Adventure Mirrors. These
        are a game changer for off-road riding - robust and offer great rear
        visibility.
  - vars:
      post: >-
        Has anyone tried the Rally Raid tank kit on their 701? I'm thinking
        about extending my range for longer trips and heard good things about
        it. Also, I upgraded my suspension with an Ohlins rear shock and the
        difference in ride quality is unbelievable. Thinking of adding a
        Scottoiler automatic chain oiler to reduce maintenance time.
  - vars:
      post: >-
        I couldn't resist the urge to modify my 701 for a more adventure-ready
        setup. First off, I added a Perun Moto luggage rack for extra storage
        space. Then, decided to upgrade the headlights to a Baja Designs
        Squadron Pro LED for better night visibility. Lastly, I'm considering a
        Garmin Zumo XT GPS for navigation. Has anyone had experience with
        mounting it on a 701?
  - vars:
      post: >-
        Just installed the Rade Garage dashboard upgrade on my 701 and I'm
        loving the extra space for navigation gadgets. Also, thrown on a Scotts
        Steering Damper which has made a world of difference on those long
        gravel runs. Can't recommend them enough for anyone looking to make
        their 701 more adventure-ready.
  - vars:
      post: >-
        I've swapped the stock exhaust for an Akrapovic Slip-On and it's not
        just the sound that's improved. Noticeable difference in responsiveness.
        For luggage, I went with the Mosko Moto Reckless 80 Revolver system.
        Totally changes the game for carrying gear without needing hard cases.
  - vars:
      post: >-
        Noticed a lot of you talking about tire choices. I've been running Mitas
        E-09 Dakar tires on mine for the last season. Fantastic durability and
        grip off-road. Also added a Rally Raid Evo2 Adventure Kit for better
        suspension and fuel capacity. It's like a different bike now.
