---

prompts:
  - |
    You are an AI assistant designed to consolidate lists of motorcycle parts and accessories from the ADVRider forum. Your task is to merge the parts and accessories lists from two different posts, ensuring that the final list is free of duplicates.

    ## INSTRUCTIONS:

    - Each item in the list has to include the brand (<BRAND>) and a brief description (<DESC>) of the part or accessory.
    - Each item should be on the form "<BRAND>: <DESC>".
    - If an input is marked as "<NOPE>", treat it as an empty list during the merging process.
    - Combine the two lists of parts and accessories, eliminating any duplicate entries.
    - If an item from the same brand appears in both lists, retain only one instance in the final list.
    - If the merged list is empty after the process, return "<NOPE>" as the output.
    - If two items have different brand names but serve the same function, include both in the final list.
    - Aim for brevity in the final list and its descriptions.
    - Do NOT prefix the output with any additional text

    ## EXAMPLES:

    Input 1:

    I'm resisting putting a Rekluse Clutch in the 701 as I'm trying to avoid tempting myself to do more technical stuff than 4wd roads. I have my 450 for that type of stuff and will probably add a Rekluse to that at some point. I had a Rekluse Auto Clutch in my old 400XC and it was great for that. I'm ready to spend what I need to make the 701 run like I want it too.

    I have about 3-4k miles on my Wings and I recently noticed it getting slightly louder. Must be getting close to a repack. Still, it's WAY quieter than the intake noise from the Rade Garage aux fuel tank kit intake. The Wings with the quietest insert made the bike a bit louder, the intake made it quite a bit louder.

    Output 1:

    - Rekluse Auto Clutch: Automatic clutch suitable for challenging terrains
    - Wings Exhaust: Exhaust system known for its quiet operation

    Input 2:

    <NOPE>

    I have about 3-4k miles on my Wings and I recently noticed it getting slightly louder. Must be getting close to a repack. Still, it's WAY quieter than the intake noise from the Rade Garage aux fuel tank kit intake. The Wings with the quietest insert made the bike a bit louder, the intake made it quite a bit louder.

    Output 2:

    - Wings Exhaust: Exhaust system known

    ## INPUT:

    {{post1}}
    {{post2}}

defaultTest:
  options:
    provider: openai:chat:gpt-4-turbo-preview

providers:
  - id: openai:chat:gpt-3.5-turbo
    label: gpt-3-5-turbo-temp-0-0
    config:
      temperature: 0.1
scenarios:
  - config:
    - vars:
        post1: >-
          - Fork Saver zip on fork socks: Protective covers for forks
          - Steg Pegz: Foot pegs designed for standing
          - Seat Concept Seat: Comfortable motorcycle seat
          - Wings Exhaust: Performance exhaust system
        post2: >-
          - Wings Exhaust: Performance exhaust system
          - Wings carbon exhaust cover: Carbon cover for exhaust system
          - Perun rear plate + extension: Secure rear plate with extension
          - Vanasche Motorsports Shortened Kickstand: Shortened kickstand for better balance
        gadgets: >-
          - Fork Saver zip on fork socks: Protective covers for forks
          - Steg Pegz: Foot pegs designed for standing
          - Seat Concept Seat: Comfortable motorcycle seat
          - Wings Exhaust: Performance exhaust system
          - Wings carbon exhaust cover: Carbon cover for exhaust system
          - Perun rear plate + extension: Secure rear plate with extension
          - Vanasche Motorsports Shortened Kickstand: Shortened kickstand for better balance
    tests:
      - assert:
        - type: factuality
          value: "{{gadgets}}"
        - type: llm-rubric
          value: No wrapper text followed by :, like "<START>Output:", "<START>Commit message:" or "<START>##"
        - type: llm-rubric
          value: "Ensure output has a similar mening to {{gadgets}}, exluding duplicates"
        - type: llm-rubric
          value: "Ensure all elements in {{post1}} and {{post2}} are is included to some extent in the output"

tests:
- vars:
    post1: |-
      - Akrapovic Exhaust: Enhances performance and sound
      - Michelin Tires: Improved grip for all weather conditions
      - Brembo Brakes: High performance braking system
      - Ohlins Suspension: Superior ride and handling
    post2: |-
      - DID Chain: Durable and high-quality motorcycle chain
      - Brembo Brakes: High performance braking system
      - Rizoma Mirrors: Stylish and functional design
- vars:
    post1: <NOPE>
    post2: |-
      - Givi Top Case: Adds significant storage capacity
      - Heidenau Tires: Known for their durability on and off-road
      - Garmin GPS Mount: Essential for navigation on long trips
- vars:
    post1: |-
      - Barkbusters Handguards: Protection for hands and levers from impacts
      - Sena Intercom: Allows for communication between riders
      - K&N Air Filter: Improves airflow and performance
    post2: |-
      - Motul Engine Oil: High-quality lubrication for engine components
      - Sena Intercom: Allows for communication between riders
      - Pirelli Tires: Offers excellent traction and durability
- vars:
    post1: |-
      - Akrapovic: High-performance exhaust system
      - Brembo: Premium brake calipers for enhanced stopping power
    post2: |-
      - Brembo: Advanced braking technology calipers
      - Ohlins: Superior suspension for optimal handling
- vars:
    post1: <NOPE>
    post2: |-
      - Michelin: Road 5 tires for improved grip in wet and dry conditions
      - Givi: Top case for additional storage space
- vars:
    post1: |-
      - Scottoiler: Automatic chain lubrication system for extended chain life
      - Garmin: Zumo XT, rugged motorcycle navigator
    post2: |-
      - Garmin: Zumo XT GPS for adventurous rides
      - Barkbusters: Handguard kit for protection against the elements
- vars:
    post1: |-
      - KTM Hard Parts: Unbreakable levers designed for off-road use
      - GoPro: Latest model for capturing ride footage
      - Pirelli: Scorpion MX tires for enhanced grip on dirt
    post2: |-
      - Garmin: Zumo GPS designed specifically for motorcycles
      - KTM Hard Parts: Unbreakable levers designed for off-road use
      - Sena: 50S Bluetooth headset for helmet communication
- vars:
    post1: <NOPE>
    post2: |-
      - Yamaha: Factory racing t-shirt
      - Michelin: Road 5 tires for superior wet grip
      - Shoei: RF-1200 full face helmet known for comfort and safety
- vars:
    post1: |-
      - Acerbis: X-Grip frame guards to protect against scratches
      - Bridgestone: Battlax Hypersport tires for quick response and high grip
      - Motul: 7100 synthetic engine oil for high-performance engines
    post2: >-
      - Ducati Performance: Termignoni exhaust system for enhanced sound and
      power

      - Acerbis: X-Grip frame guards to protect against scratches

      - Alpinestars: Tech-Air 5 airbag system for impact protection
